# WSLカーネル安定版リリース監視ツール 設定ファイル
# 要件5.1, 5.2, 5.3, 5.4に対応

[general]
# 実行モード: "continuous" (常駐) または "oneshot" (ワンショット)
execution_mode = "oneshot"

# チェック間隔（分）
check_interval_minutes = 30

# 監視対象リポジトリ
repository_url = "microsoft/WSL2-Linux-Kernel"

[notification]
# 通知機能の有効化
enabled = true

# 通知クリック時のアクション設定
[notification.click_action]
# ビルドアクションの有効化
enable_build_action = false

[logging]
# ログレベル (DEBUG, INFO, WARNING, ERROR, CRITICAL)
level = "INFO"

# ログファイルの最大サイズ（MB）
max_file_size_mb = 10

# 保持するログファイル数
backup_count = 5