# WSL Kernel Watcher 設定ファイルテンプレート
# このファイルをconfig.tomlとしてコピーして使用してください

# チェック間隔（分）
# デフォルト: 30分
check_interval_minutes = 30

# 監視対象リポジトリ
# デフォルト: "microsoft/WSL2-Linux-Kernel"
repository_url = "microsoft/WSL2-Linux-Kernel"

# ビルドアクション有効化
# 通知クリック時にWSLでビルドスクリプトを実行するかどうか
# デフォルト: false
enable_build_action = false

# 通知機能有効化
# Windowsトースト通知を表示するかどうか
# デフォルト: true
notification_enabled = true

# ログレベル
# 利用可能な値: "DEBUG", "INFO", "WARNING", "ERROR"
# デフォルト: "INFO"
log_level = "INFO"

# 設定例:
# より頻繁にチェックしたい場合
# check_interval_minutes = 15

# 別のリポジトリを監視したい場合
# repository_url = "your-username/your-repository"

# デバッグ情報を詳細に出力したい場合
# log_level = "DEBUG"

# 通知を無効にしたい場合
# notification_enabled = false

# ビルドアクションを有効にしたい場合（上級者向け）
# enable_build_action = true