services:
  wsl-kernel-watcher:
    build: .
    container_name: wsl-kernel-watcher
    restart: unless-stopped
    environment:
      - REPOSITORY_URL=microsoft/WSL2-Linux-Kernel
      - CHECK_INTERVAL_MINUTES=30
      - LOG_LEVEL=INFO
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
    volumes:
      # WSL環境でのWindows通知アクセス
      - /mnt/c/Windows/System32/WindowsPowerShell:/mnt/c/Windows/System32/WindowsPowerShell:ro
    network_mode: host
    # WSL環境での実行を前提とした設定
    command: >
      sh -c "
      if [ -f /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe ]; then
        echo 'WSL環境検出: Windows PowerShell利用可能';
        uv run python -m src.main;
      else
        echo 'WSL環境ではありません: 通知機能無効で実行';
        uv run python -m src.main;
      fi
      "