# WSL Kernel Watcher 設定ファイル
# このファイルはアプリケーションの動作を制御します

[general]
execution_mode = "continuous"
check_interval_minutes = 30
repository_url = "microsoft/WSL2-Linux-Kernel"

[notification]
enabled = true

[notification.click_action]
enable_build_action = false

[logging]
level = "INFO"
