version: '3.8'

services:
  github-watcher:
    build: .
    container_name: github-watcher
    environment:
      - MCP_GITHUB_URL=http://github-mcp:3000
      - NOTIFICATION_URL=http://host.docker.internal:9999/notify
      - CHECK_INTERVAL=1800  # 30分
    volumes:
      - ./config:/app/config:ro
    depends_on:
      - github-mcp
    restart: unless-stopped
    networks:
      - mcp-network

  github-mcp:
    image: mcp-github-server:latest
    container_name: github-mcp
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "3000:3000"
    networks:
      - mcp-network

networks:
  mcp-network:
    external: true